services:
  waha:
    container_name: waha
    image: devlikeapro/waha:arm
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - waha_data:/app/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --appendonly yes
      --appendfilename "appendonly.aof"
      --appendfsync everysec
      --save 300 10
      --loglevel warning
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_1
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API (optional)
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

volumes:
  waha_data:
  redis_data:
  qdrant_storage: