services:
  waha:
    container_name: waha
    image: devlikeapro/waha-plus:arm
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - waha_data:/app/data
    restart: unless-stopped

  agent-memory-api:
    build:
      context: ./agent-memory-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env      
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LONG_TERM_MEMORY=True
      - WINDOW_SIZE=20
      - GENERATION_MODEL=gpt-4o-mini
      - EMBEDDING_MODEL=text-embedding-3-small
      - ENABLE_TOPIC_EXTRACTION=True
      - ENABLE_NER=True
    depends_on:
      - redis
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/v1/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  agent-memory-mcp:
    build:
      context: ./agent-memory-server
      dockerfile: Dockerfile
    env_file:
      - .env      
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=9000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LONG_TERM_MEMORY=True
      - WINDOW_SIZE=20
      - GENERATION_MODEL=gpt-4o-mini
      - EMBEDDING_MODEL=text-embedding-3-small
      - ENABLE_TOPIC_EXTRACTION=True
      - ENABLE_NER=True
    ports:
      - "9000:9000"
    depends_on:
      - redis
    command: ["uv", "run", "agent-memory", "mcp", "--mode", "sse"]

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"  # Redis port
      - "8001:8001"  # RedisInsight port
    volumes:
      - redis_data:/data
    command: redis-stack-server --save 60 1 --loglevel warning
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  waha_data:
  redis_data: