services:
  waha:
    container_name: waha
    image: devlikeapro/waha-plus:arm
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - waha_data:/app/data
    restart: unless-stopped


  db:
    image: pgvector/pgvector:pg17          # Postgres + pgvector baked in
    container_name: letta-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: letta                # default DB that Letta will use
      POSTGRES_USER: letta
      POSTGRES_PASSWORD: letta_pass
    ports:
      - "5432:5432"                     # expose locally; drop if not needed
    volumes:
      - pg_data:/var/lib/postgresql/data  # persistent data
      # run any *.sql scripts on first init (creates the extension)
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U letta"]
      interval: 10s
      timeout: 5s
      retries: 5
  letta:
    image: letta/letta:latest
    container_name: letta
    env_file:
      - .env
    environment:
      LETTA_PG_URI: postgresql://letta:letta_pass@db:5432/letta
    ports:
      - "8283:8283"
    depends_on:
      db:
        condition: service_healthy 
  pgadmin:
    image: dpage/pgadmin4:latest
    # container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev     # change as needed
      PGADMIN_DEFAULT_PASSWORD: admin123         # change this too
    ports:
      - "5050:80"                                 # access via http://localhost:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  waha_data:
  pg_data:
  pgadmin_data:
  # redis_data:
  # qdrant_data: