services:
  waha:
    image: devlikeapro/waha:arm
    ports:
      - "3000:3000"
    environment:
      - WAHA_API_KEY=your-waha-api-key
      - WAHA_WEBHOOK_URL=http://host.docker.internal:5002/webhook
      - WAHA_PRINT_QR=false

    volumes:
      - waha_data:/app/data
    restart: unless-stopped

volumes:
  waha_data: