services:
  waha:
    image: devlikeapro/waha:arm
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - waha_data:/app/data
    restart: unless-stopped


volumes:
  waha_data:
  memobase_data: